### ISSUE TITLE
Unable to add a new feature module

### ISSUE THREAD

**Issue by pmdauv** [MarkPieszak/aspnetcore-angular2-universal#173]
Hi. 
I'm new in angular development app. I'm implementing an app by using *NEW* Angular 2+ Universal & ASP.NET Core Advanced Starter. When I add a new feature module, there are issues from the main-server.js file like this one:
« Exception: Call to Node module failed with error: ReferenceError: document is not defined
at DefaultDomRenderer2.selectRootElement.
(C:\Workspace\Developments\WebApps\New\GoldenlightITApp\Client\dist\main-server.js:32413:72)
at createElement (C:\Workspace\Developments\WebApps\New\GoldenlightITApp\Client\dist\main-server.js:9611:23)
at createViewNodes (C:\Workspace\Developments\WebApps\New\GoldenlightITApp\Client\dist\main-server.js:12214:44)
at createRootView (C:\Workspace\Developments\WebApps\New\GoldenlightITApp\Client\dist\main-server.js:12161:5)
at Object.createProdRootView [as createRootView] (C:\Workspace\Developments\WebApps\New\GoldenlightITApp\Client\dist\main-server.js:12739:12)
at ComponentFactory_.create (C:\Workspace\Developments\WebApps\New\GoldenlightITApp\Client\dist\main-server.js:10097:46)
at ComponentFactoryBoundToModule.create »

I would like to know if there is a tool to generate main-server.js file or it's generated manually. Will you help me to solve this issue.

Regards.

**Comment by pjmagee** [comment]
Have you run webpack? This should be triggered as a part of the `> dotnet publish`

**Comment by MarkPieszak** [comment]
Yeah, try `npm run build:dev` to build the webpack dev bundles.
