### ISSUE TITLE
Exception: Call to Node module failed with error: reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by darklx** [MarkPieszak/aspnetcore-angular2-universal#24]
Hello,

Get an error:

<img width="944" alt="screen shot 2016-11-17 at 7 12 54 pm" src="https://cloud.githubusercontent.com/assets/3222379/20387185/e67cde34-acf9-11e6-9b79-68967167d6fa.png">

but It's ok to use webpack build:
<img width="452" alt="screen shot 2016-11-17 at 7 12 49 pm" src="https://cloud.githubusercontent.com/assets/3222379/20387191/ece5535a-acf9-11e6-9984-e0e1ce481798.png">

**The project's npm dependices restoring output:**
<img width="704" alt="screen shot 2016-11-17 at 7 21 51 pm" src="https://cloud.githubusercontent.com/assets/3222379/20387490/4d2e2c5e-acfb-11e6-9d2c-c70ec65d802f.png">

**Environment**
npm -v
3.8.2

node -v
v4.4.1

**Exception Stack**
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor:Information: Executing ViewResult, running view at path /Views/Home/Index.cshtml.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\darkl\.nuget\packages\Microsoft.AspNetCore.WebUtilities\1.0.0\lib\netstandard1.3\Microsoft.AspNetCore.WebUtilities.dll'. Loading disabled by Include/Exclude setting.
Microsoft.Extensions.DependencyInjection.DataProtectionServices:Information: User profile is available. Using 'C:\Users\darkl\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.Reflection.Emit.dll'. Loading disabled by Include/Exclude setting.
Microsoft.AspNetCore.NodeServices:Information: Node will restart because file changed: F:\git\aspnetcore-angular2-universal\wwwroot\dist\main.js
Microsoft.AspNetCore.NodeServices:Information: webpack built 396559ce6e3756fbe2a7 in 9638ms
Microsoft.AspNetCore.NodeServices:Information: [default] Checking started in a separate process...
Microsoft.AspNetCore.NodeServices:Information: [default] Ok, 5.798 sec.
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in Microsoft.AspNetCore.NodeServices.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in Microsoft.AspNetCore.Mvc.Core.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in Microsoft.AspNetCore.Mvc.Core.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.Diagnostics.StackTrace.dll'. Loading disabled by Include/Exclude setting.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.IO.MemoryMappedFiles.dll'. Loading disabled by Include/Exclude setting.
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.ni.dll
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.IO.UnmanagedMemoryStream.dll'. Loading disabled by Include/Exclude setting.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

System.Exception: Call to Node module failed with error: reflect-metadata shim is required when using class decorators
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.SpaServices.Prerendering.PrerenderTagHelper.<ProcessAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AspNetCore._Views_Home_Index_cshtml.<ExecuteAsync>d__32.MoveNext() in /Views/Home/Index.cshtml:line 2
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderPageAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.<RenderAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultFilterAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllResultFiltersAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResourceFilterAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 17725.885ms 500 text/html; charset=utf-8

**Comment by MarkPieszak** [comment]
@darklx Hey there, so this is a fairly common install issue that stems from an older version of NPM. You'll need npm 3.*+. You can do `node --version && npm --v` to see what you currently have. 

If you go and install the latest Node, 7.1, you should be able to install everything over again without any problems. Just make sure to wipe out your node_modules beforehand.

Thanks for reminding me I'll make sure to add the strictEngine warnings to help prevent things like this!

Hope that helps, let me know!

**Comment by darklx** [comment]
When I upgrade to node 7.0,0 It's OK,than you !!!

**Comment by MarkPieszak** [comment]
Glad to hear it. Keep an eye out for more updates to come. Doing some general clean-up, and trying to get some more real-world examples in here as soon as I can.

**Comment by darklx** [comment]
Cool !!
