### ISSUE TITLE
Exception: Call to Node module failed with error

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#254]
Excuse my English

I have had several problems using this template, some solved with these commands:

npm rebuild node-sass
npm run build: dev

Other times I delete the folder node_modules and execute npm install and commands again

But it is very complicated that from one moment to another without making any changes in the code begin to emerge errors

Now the problem is this:

"An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Prerendering timed out after 30000ms because the boot function in '../Client/dist/main-server' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper."

I am very frustrated, because I have hours, maybe days with these problems and none is for my code ... explain this to your boss ...

Anyway ... thanks and I hope to move on with this

**Comment by DotNetDev1** [comment]
I'm having the same issue.  Spent the past two days trying to configure my development environment to get this project to build and run and haven't made much headway...Your instructions say that you can open the project in "VS 2017 and simply push F5 to start debugging", but all of my web requests fail with the message "Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x.  Found bindings for the following environments: Windows 64-bit with Node.js 5.x".  I've tried rebuilding node-sass, reinstalling node modules, and a bunch of other things and nothing I do has allowed the server app to respond to http requests.  The project looks like a promising way to bootstratp an Angular 4.x / ASP.Net project, but it would be helpful include instructions on how to configure your dev environment for newbies like myself.

**Comment by cristiancamiloperezlopez** [comment]
Jesus Christ

In my case, this error was coming out of a comment from a .css file of a component

Apparently webpack when loading the css does not exclude the lines that are comments ... the solution was to delete the comments

Now I have another problem

I create a component and add some html, then compile webpack and everything without problems, I execute the project and the HTML looks good, renders well

But when I log in to developer tools I see this error

![error](https://cloud.githubusercontent.com/assets/25587867/26005831/e3fe27cc-36ff-11e7-85e9-2fb8b252969b.png)

I think it's related to [HMR] ...

The strange thing is that when I change my html for something very simple, like

<H1> component </ h1>

Fixed bug in developer tools

**Comment by j-nord** [comment]
I have the same issue.   (node 7.10, npm 4,2.0)
There are two many errors:

> angular4-aspnetcore-universal@1.0.0-rc3 build:dev C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master
> webpack --progress --color

Hash: [1m3956f0e8ecb585519ac22666bfe356e8649d4d46[39m[22m
Version: webpack [1m2.5.1[39m[22m
Child
    Hash: [1m3956f0e8ecb585519ac2[39m[22m
    Time: [1m27472[39m[22mms
                  [1mAsset[39m[22m     [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m       [1mChunk Names[39m[22m
                   [1m[32m0.js[39m[22m   3.3 kB       [1m0[39m[22m  [1m[32m[emitted][39m[22m         
        [1m[33mmain-browser.js[39m[22m  [1m[33m3.99 MB[39m[22m       [1m1[39m[22m  [1m[32m[emitted][39m[22m  [1m[33m[big][39m[22m  main-browser
               [1m[32m0.js.map[39m[22m  1.51 kB       [1m0[39m[22m  [1m[32m[emitted][39m[22m         
    [1m[32mmain-browser.js.map[39m[22m  4.75 MB       [1m1[39m[22m  [1m[32m[emitted][39m[22m         main-browser
       [1] [1m./~/@angular/core/@angular/core.es5.js[39m[22m 467 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
       [3] [1m./~/rxjs/Observable.js[39m[22m 5.64 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
      [30] [1m./~/rxjs/Subject.js[39m[22m 5.61 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
      [31] [1m./~/@angular/platform-browser/@angular/platform-browser.es5.js[39m[22m 142 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
      [76] [1m(webpack)/buildin/global.js[39m[22m 509 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
      [79] [1m./Client/app/shared/constants/baseurl.constants.ts[39m[22m 153 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [126] [1m./~/ng2-signalr/index.js[39m[22m 524 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [141] [1m./Client async[39m[22m 160 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [143] [1m./Client/app/shared/constants/request.ts[39m[22m 137 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [382] [1m./~/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js[39m[22m 6.09 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [383] [1m./Client/app/browser-app.module.ts[39m[22m 2.83 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [384] [1m./Client/polyfills/browser.polyfills.ts[39m[22m 128 bytes {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [399] [1m./Client/main.browser.ts[39m[22m 1.02 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [402] [1m./Client/polyfills/polyfills.ts[39m[22m 1.16 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
     [595] [1m./~/reflect-metadata/Reflect.js[39m[22m 48 kB {[1m[33m1[39m[22m}[1m[32m [built][39m[22m
        + 640 hidden modules
    
    [1m[31mERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./Client/app/app.component.scss
    Module build failed: Error: Missing binding C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-51\binding.node
    Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x
    
    Found bindings for the following environments:
      - Windows 64-bit with Node.js 5.x
    
    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass --force` to build the binding for your current environment.
        at module.exports (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\binding.js:15:13)
        at Object.<anonymous> (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at loadLoader (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\webpack\lib\Compilation.js:146:10)
        at factoryCallback (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\webpack\lib\Compilation.js:329:11)
        at factory (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\webpack\lib\NormalModuleFactory.js:253:5)
        at applyPluginsAsyncWaterfall (C:\Users\JÃ¼rgen\Documents\Visual Studio 2017\Projects\aspnetcore-angular2-universal-master\node_modules\webpack\lib\NormalModuleFactory.js:99:14)
     @ ./Client/app/app.component.scss 2:21-138
     @ ./Client/app/app.component.ts
     @ ./Client/app/browser-app.module.ts
     @ ./Client/main.browser.ts[39m[22m
Child
    Hash: [1m2666bfe356e8649d4d46[39m[22m
    Time: [1m27462[39m[22mms
             [1mAsset[39m[22m     [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m           [1m[39m[22m       [1mChunk Names[39m[22m
              [1m[32m0.js[39m[22m  5.37 kB       [1m0[

**....**

**Comment by MarkPieszak** [comment]
@j-nord Did you run `npm rebuild node-sass --force`? It appears you have multiple Nodes installed and you must have at *least* 6+, so you need to rebuild it. This is a strange workflow issue with node-sass itself :(

**Comment by DotNetDev1** [comment]
Got it working on my machine.  Had to run npm install and npm rebuild from the windows command line rather than within visual studio 2017 as the visual studio version kept generating random errors and had trouble downloading packages from the internet.  Also had to install and run webpack.  Once these tasks were complete the server app began properly responding to http requests and serving web pages.

**Comment by MarkPieszak** [comment]
It's because VS comes with its own (very old) version of node. There is a way to change it to always use your $(PATH) version though.

**Comment by j-nord** [comment]
Thanks Mark  "npm rebuild node-sass " helps.

**Comment by MarkPieszak** [comment]
Hoping VS fixes some these underlying issues like the self installed (old versions of Node), and that node-sass finds a way to rebuild itself when it's not sure which version is running as well.

When in doubt, always just use your terminal, not a terminal inside VS !

Can we close this one out now? 
If there are any other specific issues for you guys, just open up a new issue so we can figure it out? 🎈

@DotNetDev1 Don't worry, the repo will get easier in time 👍

**Comment by DotNetDev1** [comment]
Than you @MarkPieszak !
