### ISSUE TITLE
Error: Cannot assign to a reference or variable!

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#293]
How can i find where this error occurs? I can't figure this out :(

`System.Exception: Call to Node module failed with error: Error: Cannot assign to a reference or variable!
    at _AstToIrVisitor.visitPropertyWrite (C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:89723:23)
    at PropertyWrite.visit (C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:71560:24)
    at convertActionBinding (C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:89281:45)
    at C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:90982:22
    at Array.forEach (native)
    at ViewBuilder._createElementHandleEventFn (C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:90978:18)
    at nodes.(anonymous function) (C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:90526:23)
    at C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:90928:22
    at Array.map (native)
    at ViewBuilder._createNodeExpressions (C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server.js:90927:56)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---`

**Comment by digibum** [comment]
Found the problem... component and template used same variable names... Can't have that.
Tnx.

**Comment by achmedzhanov** [comment]
Need more detailed message

**Comment by soulblue93** [comment]
@achmedzhanov 
For example

```
<mat-button-toggle-group #example="matButtonToggleGroup" [(ngModel)]="example">
          <mat-button-toggle value="yes">
            Yes
          </mat-button-toggle>
          <mat-button-toggle value="no">
            No
          </mat-button-toggle>
</mat-button-toggle-group>
```
If we change **#example** by **#exampleLocal** it will be the solution.

**Comment by eliteproxy7** [comment]
how can we trace this to see which component its coming from?
