### ISSUE TITLE
Debugging Tips

### ISSUE THREAD

**Issue by kyse** [MarkPieszak/aspnetcore-angular2-universal#300]
Curious if you have any debugging tips for items that do not bubble up to the error output to the page.

I'm noticing some odd things here and there. 

```
Microsoft.AspNetCore.NodeServices:Error: ERROR TypeError: Cannot read property 'apply' of undefined
    at RendererAdapter.a../node_modules/@angular/core/@angular/core.es5.js.RendererAdapter.invokeElementMethod (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:48346:38)
    at Timeout.AutoFocusDirective.setTimeout (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:2103:22)
    at ZoneDelegate.a../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:123796:31)
    at Object.onInvokeTask (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:41931:37)
    at ZoneDelegate.a../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:123795:36)
    at Zone.a../node_modules/zone.js/dist/zone-node.js.Zone.runTask (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:123563:47)
    at Timeout.ZoneTask.invoke (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:123858:38)
    at Timeout.timer [as _onTimeout] (C:\Users\kyse\Source\Repos\App\src\App\Client\dist\main-server.js:124852:29)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
```

This particular error occurs after the initial request to the site.

Then there's an error every time I ht refresh while debugging, most likely related to HMR.  I'd guess HMR does not cancel the websocket during a browser refresh.  Kind of annoying to see it spam the debug output when refreshing the page.

Then again perhaps this is just debug loggout input from kestrel middleware that should be marked info and not debug.

```
Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor:Information: Executing JsonResult, writing value System.Collections.Generic.Dictionary`2[System.String,System.Object].
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action App.Server.RestAPI.TranslationsController.Get (App) in 49.7701ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 56.0283ms 200 application/json; charset=utf-8
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:56991/__webpack_hmr  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:56991/favicon.ico  
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Information: Sending file. Request path: '/favicon.ico'. Physical path: 'C:\Users\kyse\Source\Repos\App\src\App\wwwroot\favicon.ico'
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 5.6943ms 200 image/x-icon
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Warning: The response has already started, the error page middleware will not be executed.
Microsoft.AspNetCore.Server.Kestrel:Error: Connection id "0HL5G85RH8B0T": An unhandled exception was thrown by the application.

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<PerformProxyRequest>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 999048.504ms 200 text/event-stream; charset=utf-8
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:56991/dist/4216e31a233e6c5ec6e8.hot-update.json  
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 8.7846ms 404 text/plain
```

**Comment by kyse** [comment]
Also, how do you suggest the best option for handling content that requires authenticated API calls.  I'm running into issues with rendering timeouts where the page makes api calls that are locked down.  I've tried using an HttpOptions override service to add the injected REQUEST.cookie into http request headers, but still getting problems with render timeouts.  Not sure the authentication cookies are being transferred to the server rendering, only the XSRF-TOKEN cookie appears to be making it to the server and into my HttpOptions service.

**Comment by MarkPieszak** [comment]
Do you have some properties/attributes that are being passed the value Null by any chance? We have a bug logged for platform-server for scenarios like that, wondering if that's he unknown error you're seeing ?

As for general debugging, if errors don't reach the browser error they should at least be in the Node output logged (either in command line or debug windows, however you launched the App).

We are also using tools based on JavaScriptServices here, so you can debug your server side rendered Typescript code as it runs via node-inspector as well to see if you can pinpoint it there. Some more info here: https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#debugging-your-javascripttypescript-code-when-it-runs-on-the-server

As for Auth issues those are typically just quite tough, you want to pass in some kind of Auth token from your HomeController into main.server (though that TransferData class that's in Home Controller). It's then available via `params.data`(Whatever object you added onto it is available there, `params.data.authKey` let's say.  Now you could just provide a fake Token here, and make sure your Http calls Use it when it's platformServer (the Readme shows how to test for that in the FAQ section). Provide the token an easier way like: 

    { provide: serverAuthToken: useValue: params.data.authKey }

That should get you where you need to be!

**Comment by kyse** [comment]
I think I found the issue.

I noticed when calling the translation endpoint, it would call the injected TransferHttpOptions (verified via console.log() msg I saw in the output window.  But the calls routing through transfer-http module are ignoring the TransferHttpOptions, thus the cookies aren't being supplied to the request.  Looks like the Transfer-Http constructor requests the settings, it just doesn't do anything with them.

**Comment by MarkPieszak** [comment]
Ah you're saying for the server calls it ignores them? Yeah I'm not sure if they get used during server renders, its mainly for re-using http calls in the client.

Did you end up fixing your issue? Let me know if it's something we should include in the template!
