### ISSUE TITLE
dotnet publish error

### ISSUE THREAD

**Issue by vfportero** [MarkPieszak/aspnetcore-angular2-universal#360]
Hi Mark,

I'm having this error when try to execute dotnet publish before upload Azure:

> EXEC : error : Cannot find module 'E:\Repositories\GitHub\escapistas.club\src\EscapistasClub.Web.Angular4\webpack.config.vendor.js' [E:\Repositories\GitHub\escapistas.club\src\EscapistasClub.Web.Angular4\EscapistasClub.Web.Angular4.csproj]
at Function.Module._resolveFilename (module.js:469:15)
      at Function.Module._load (module.js:417:25)
      at Module.require (module.js:497:17)
      at require (internal/module.js:20:19)
      at requireConfig (E:\Repositories\GitHub\escapistas.club\src\EscapistasClub.Web.Angular4\node_modules\webpack\bin\convert-argv.js:96:18)
      at E:\Repositories\GitHub\escapistas.club\src\EscapistasClub.Web.Angular4\node_modules\webpack\bin\convert-argv.js:109:17
      at Array.forEach (native)
      at module.exports (E:\Repositories\GitHub\escapistas.club\src\EscapistasClub.Web.Angular4\node_modules\webpack\bin\convert-argv.js:107:15)
      at Object.<anonymous> (E:\Repositories\GitHub\escapistas.club\src\EscapistasClub.Web.Angular4\node_modules\webpack\bin\webpack.js:153:40)
      at Module._compile (module.js:570:32)

This is my repo: https://github.com/vfportero/escapistas.club

Any idea?

Thanks!

**Comment by MarkPieszak** [comment]
Currently there is no webpack.vendor file, is this a merge of JSServices & this repo?
Check your csproj file, there must be something in there calling webpack with webpack.vendor, you could probably remove it and it'll get rid of that error.

Let me know!
