### ISSUE TITLE
npm rebuild node-sass --force fails with The Windows SDK version 8.1 was not found.

### ISSUE THREAD

**Issue by MaklaCof** [MarkPieszak/aspnetcore-angular2-universal#392]
After a few months I re-download this repo and now I am trying to merge it with my existing code.
After I run F5 in visual studio, JS Console report I should run `npm rebuild node-sass --force`.
After install Python version 2.7.13 (because I get error executable not found) (old code was working with version 3) I get a new error:
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the req
uired version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [e:\OpPISWeb\OpPISWeb\node_module
s\node-sass\build\src\libsass.vcxproj]

Build FAILED.

"e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(Desktop_PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the r
equired version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [e:\OpPISWeb\OpPISWeb\node_modu
les\node-sass\build\src\libsass.vcxproj]
```

Can anyone help me. I don't have a clue what should I do.

Complete log:

```
e:\OpPISWeb\OpPISWeb>npm rebuild node-sass --force
npm WARN using --force I sure hope you know what you are doing.

> node-sass@4.5.3 install e:\OpPISWeb\OpPISWeb\node_modules\node-sass
> node scripts/install.js

node-sass build Binary found at e:\OpPISWeb\OpPISWeb\node_modules\node-sass\vendor\win32-x64-51\binding.node

> node-sass@4.5.3 postinstall e:\OpPISWeb\OpPISWeb\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe e:\OpPISWeb\OpPISWeb\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@7.10.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:80:29)
gyp verb `which` failed     at e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:89:16
gyp verb `which` failed     at e:\OpPISWeb\OpPISWeb\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at e:\OpPISWeb\OpPISWeb\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:80:29)
gyp verb `which` failed     at e:\OpPISWeb\OpPISWeb\node_modules\which\which.js:89:16
gyp verb `which` failed     at e:\OpPISWeb\OpPISWeb\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at e:\OpPISWeb\OpPISWeb\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:114:15)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (e:\\OpPISWeb\\OpPISWeb\\node_modules\\which\\which.js:13:12)\n    at F (e:\\OpPISWeb\\OpPISWeb\\node_modules\\which\\which.js:68:19)\n    at E (e:\\OpPISWeb\\OpPISWeb\\node_modules\\which\\which.js:80:29)\n    at e:\\OpPISWeb\\OpPISWeb\\node_modules\\which\\which.js:89:16\n    at e:\\OpPISWeb\\OpPISWeb\\node_modules\\isexe\\index.js:42:5\n    at e:\\OpPISWeb\\OpPISWeb\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:114:15)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\matjaz.cof\AppData\Local\Programs\Python\Python36-32\python.EXE
gyp verb check python version `C:\Users\matjaz.cof\AppData\Local\Programs\Python\Python36-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.1\r\n"
gyp verb could not find "C:\Users\matjaz.cof\AppData\Local\Programs\Python\Python36-32\python.EXE". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print(platform.python_version());"` returned: "2.7.13\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 7.10.0
gyp verb command install [ '7.10.0' ]
gyp verb install input version string "7.10.0"
gyp verb install installing version: 7.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 7.10.0
gyp verb build dir attempting to create "build" dir: e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional
gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb find vs2017 Found installation at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
gyp verb find vs2017   - Missing Visual Studio C++ core features (Microsoft.VisualStudio.VC.MSBuild.Base)
gyp verb find vs2017   - Missing VC++ 2017 v141 toolset (x86,x64) (Microsoft.VisualStudio.Component.VC.Tools.x86.x64)
gyp verb find vs2017   - Missing a Windows SDK (Microsoft.VisualStudio.Component.Windows10SDK.* or Microsoft.VisualStudio.Component.Windows81SDK)
gyp verb find vs2017   - Some required components are missing, not using this installation
gyp verb Not using VS2017: No usable installation of VS2017 found
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: e:\OpPISWeb\OpPISWeb\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: e:\OpPISWeb\OpPISWeb\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\matjaz.cof\\.node-gyp\\7.10.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\matjaz.cof\\.node-gyp\\7.10.0',
gyp info spawn args   '-Dnode_gyp_dir=e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\matjaz.cof\\.node-gyp\\7.10.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\matjaz.cof\.node-gyp\7.10.0
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 30/08/2017 11:02:37.
Project "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.sln" (1) is building "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) on node 1 (default
 targets).
Project "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.vcxproj.metaproj" (2) is building "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\src\libsass.vcxproj" (3) on node 1
(default targets).
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the req
uired version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [e:\OpPISWeb\OpPISWeb\node_module
s\node-sass\build\src\libsass.vcxproj]
Done Building Project "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\src\libsass.vcxproj" (default targets) -- FAILED.

Done Building Project "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"e:\OpPISWeb\OpPISWeb\node_modules\node-sass\build\src\libsass.vcxproj" (default target) (3) ->
(Desktop_PlatformPrepareForBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the r
equired version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [e:\OpPISWeb\OpPISWeb\node_modu
les\node-sass\build\src\libsass.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (e:\OpPISWeb\OpPISWeb\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "e:\\OpPISWeb\\OpPISWeb\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd e:\OpPISWeb\OpPISWeb\node_modules\node-sass
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
node-sass@4.5.3 e:\OpPISWeb\OpPISWeb\node_modules\node-sass

e:\OpPISWeb\OpPISWeb>
```

**Comment by MarkPieszak** [comment]
Windows always complicates a lot of these tools, can you make sure you have the windows 8.1 sdk installed?

https://stackoverflow.com/a/43888773

Give that a try and let us know !

**Comment by MaklaCof** [comment]
I had another idea back from the xp windows experience. Restart helped and solved my problem.
