### ISSUE TITLE
AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

### ISSUE THREAD

**Issue by Sharique-Hasan** [MarkPieszak/aspnetcore-angular2-universal#567]
I had it running perfectly fine in production and development. But now I have this error coming up suddenly out of no where.

AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

```
AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (C:\WINDOWS\TEMP\e1qkeoc3.evv:83:19)
at __webpack_require__ (C:\WINDOWS\TEMP\e1qkeoc3.evv:20:30)
at createWebpackDevServer (C:\WINDOWS\TEMP\e1qkeoc3.evv:62:26)
at C:\WINDOWS\TEMP\mhnpi5fe.b3r:114:19
at IncomingMessage.<anonymous> (C:\WINDOWS\TEMP\mhnpi5fe.b3r:133:38)
at emitNone (events.js:106:13)
Current directory is: F:\my-application
)

System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
```

I removed my node_modules. Using the LTS node version. But couldn't get through. Now I am unable to deploy my app on production. What could be the reason?

**Comment by gusarov** [comment]
+1 same here

**Comment by infact** [comment]
+1 Same here   @gusarov how you got that resolved ?
