### ISSUE TITLE
NodeInvocationException: Can't resolve all parameters for AppComponent: (?, ?, ?, ?, ?)

### ISSUE THREAD

**Issue by Xoadra** [MarkPieszak/aspnetcore-angular2-universal#604]
My app throws an unhandled exception error when I run `dotnet run` when I have any dependencies injected into my AppComponent.  It works fine otherwise, however.

What I can guess at by reading the stack trace is that there may be an issue with how Webpack bundled my files.  That, and I suspect the server-side prerendering is at play here, given the `NodeInvocationException`.  Either way, I'm not sure where to go from here.

Here's the stack trace in question:
```
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Can't resolve all parameters for AppComponent: (?, ?, ?, ?, ?).
Error: Can't resolve all parameters for AppComponent: (?, ?, ?, ?, ?).
    at syntaxError (webpack-internal:///67:707:34)
    at CompileMetadataResolver._getDependenciesMetadata (webpack-internal:///67:15922:35)
    at CompileMetadataResolver._getTypeMetadata (webpack-internal:///67:15757:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (webpack-internal:///67:15242:24)
    at CompileMetadataResolver._getEntryComponentMetadata (webpack-internal:///67:16070:45)
    at eval (webpack-internal:///67:15551:110)
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (webpack-internal:///67:15551:73)
    at CompileMetadataResolver.getNgModuleSummary (webpack-internal:///67:15355:52)
    at eval (webpack-internal:///67:15453:72)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NgCore.Pre.HttpPrerender.<Prerender>d__1.MoveNext() in /Users/xoadra/Programming/Project/NgCore/Pre/HttpPrerender.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NgCore.Controllers.HomeController.<Index>d__0.MoveNext() in /Users/xoadra/Programming/Project/NgCore/Controllers/HomeController.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

As for the AppComponent itself, this is the code I have for it at the moment:
```ts
import { Component, OnInit, Injector, Inject, ViewEncapsulation, PLATFORM_ID, RendererFactory2 } from '@angular/core'
import { Router, NavigationEnd, ActivatedRoute, PRIMARY_OUTLET } from '@angular/router'
import { Title, Meta, DOCUMENT, MetaDefinition } from '@angular/platform-browser'
import { isPlatformServer } from '@angular/common'
import { Subscription } from 'rxjs/Subscription'

import { Request } from './tools/prerender'
import { REQUEST } from '@nguniversal/aspnetcore-engine'



@Component( {
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: [ './app.component.css' ],
    encapsulation: ViewEncapsulation.None
} )


export class AppComponent implements OnInit {
	
    name: string = 'NgCore'
    meta: MetaDefinition = {
        name: 'description',
        content: 'NgCore, a web app combining Angular, ASP.NET Core, and server-side rendering!'
    }
    title: string = 'app'
    angularClientSideData: string = 'Angular'
    request
    private stuff: Subscription
	
	
    constructor(
        private _meta: Meta,
        private _title: Title,
        private _route: Router,
        private _url: ActivatedRoute,
        private _inject: Injector
    ) {
        /* this.request = this._inject.get( Request( ) ) */
        this.request = this._inject.get( REQUEST )
        console.log( this.request )
    }
	
	
    ngOnInit( ) {
        /* this._title.setTitle( this.name )
        this._meta.updateTag( this.meta ) */
        this.doStuff( )
    }
	
    private doStuff( ) {
        this.stuff = this._route.events
            .filter( event => event instanceof NavigationEnd )
            .map( ( ) => this._url )
            .map( route => {
                while ( route.firstChild ) route = route.firstChild
                return route
            } )
            .filter( route => route.outlet === 'primary' )
            .mergeMap( route => route.data )
            .subscribe( ( event ) => { this._setMetaAndLinks( event ) } )
    }
	
    private _setMetaAndLinks( event ) {
        // Set Title if available, otherwise leave the default Title
        /* const title = event[ 'title' ]
            ? `${ event[ 'title' ] } - ${ this.endPageTitle }`
            : `${ this.defaultPageTitle } - ${ this.endPageTitle }`
        this.title.setTitle( title )
        const metaData = event[ 'meta' ] || [ ]
        const linksData = event[ 'links' ] || [ ]
        for ( let i = 0; i < metaData.length; i++ ) {
            this.meta.updateTag( metaData[ i ] )
        } */
        this._title.setTitle( this.name )
        this._meta.updateTag( this.meta )
    }
	
}
```
Other configurations have been tried, but to no avail.  Everything I try throws the exact same exception when I use dependency injection in my AppComponent.

Please let me know what you all think!  This issue is pure evil incarnate.

**Comment by Xoadra** [comment]
One thing of note I'll add is that I managed to successfully run the app in the production build.  Albeit I did receive some other errors still, but I got my front page to load which hasn't been happening while working off of my development build.

**Comment by MarkPieszak** [comment]
Check out this commit:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/578/files

Things were moved into `/tokens`, maybe that's part of the issue?

Either way, try and delete package-lock.json, node_modules, and reinstall everything and do an `npm run build:dev` to rebuild all your dev files all over again. Then try running, that sometimes does the trick!

**Comment by Xoadra** [comment]
> Things were moved into `/tokens`, maybe that's part of the issue?

I noticed the upgraded version of the engine earlier so I had already updated my token imports, but that didn't appear to be the problem.

> Either way, try and delete package-lock.json, node_modules, and reinstall everything and do an `npm run build:dev` to rebuild all your dev files all over again.

Looks like this didn't do it for me either.

Alternatively, I suspect I may know where there might be some issues that are causing this issue I'm having.  While troubleshooting, I came across some posts that heavily resembled the same type of problem I'm currently dealing with.  Take a look at [this](https://github.com/angular/universal/issues/877) and [this](https://github.com/aspnet/JavaScriptServices/issues/1408#issuecomment-354992270).

What I know currently is that it's an issue related to SSR, but *only* with **non**-AoT builds.  When I run this in production mode, my injected parameters resolve just fine.  For that, the AngularCompilerPlugin appears to be key.  The posts I linked also mentioned lazy loading, but I'm not sure where in my app I would have configured that.  I don't have experience working with lazy loading, so I wouldn't know where to look.

My stack trace is slightly different now too, as it's not referencing Webpack anymore.  Here it is in case you might find it useful:
```
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Can't resolve all parameters for AppComponent: (?, ?, ?, ?, ?).
Error: Can't resolve all parameters for AppComponent: (?, ?, ?, ?, ?).
    at syntaxError (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:38033:34)
    at CompileMetadataResolver._getDependenciesMetadata (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:53248:35)
    at CompileMetadataResolver._getTypeMetadata (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:53083:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:52568:24)
    at CompileMetadataResolver._getEntryComponentMetadata (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:53396:45)
    at /Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:52877:110
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:52877:73)
    at CompileMetadataResolver.getNgModuleSummary (/Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:52681:52)
    at /Users/xoadra/Programming/Project/NgCore/Angular/build/server.bundle.js:52779:72
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NgCore.Pre.HttpPrerender.<Prerender>d__1.MoveNext() in /Users/xoadra/Programming/Project/NgCore/Pre/HttpPrerender.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NgCore.Controllers.HomeController.<Index>d__0.MoveNext() in /Users/xoadra/Programming/Project/NgCore/Controllers/HomeController.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by Xoadra** [comment]
I managed to make a bit more progress on this and got my app to run properly in development mode by using `@Inject( PLATFORM_ID ) platformId: string` in my component constructor.

The problem with this is every component, service, etc. that uses dependency injection will also need the  `PLATFORM_ID` token injected into it as well instead of just injecting it once in my root component and working everywhere else in the app.  If I don't inject it everywhere, I run into the same problem.

**Comment by Xoadra** [comment]
It appears my issue was related to the order of my import statements in the boot files.  I no longer have the issues I was having before once I imported the polyfills first.  What a bizarre issue.  Looks like I need to learn more about polyfills!

I apologize for the inconvenience of all of this.  I'm still learning a lot about web development and I'm fairly new to the field.

Nonetheless, thanks for your time!  I'm glad to finally have this problem resolved.

**Comment by MarkPieszak** [comment]
I'm glad you figured it out! I'll try and add a note/comment in that file to make sure the polyfills are first. We just need them to add a lot of the missing features of browsers/etc so that everything works as it should! :+1:

**Comment by cedrica** [comment]
for me the problem was related to the fact that i assigned a param to my controller without putting a private before.
i.e. LoginComponent(route:Route) instead of LoginComponent(private route:Route).
I hope it will help
