### ISSUE TITLE
build:prod is failed

### ISSUE THREAD

**Issue by vasyliv** [MarkPieszak/aspnetcore-angular2-universal#633]
there is an issue with production:
steps to reproduce
git clone https://github.com/MarkPieszak/aspnetcore-angular2-universal.git
cd to folder
npm i
npm run build:prod
got an error
```
An unhandled exception occurred while processing the request.
NodeInvocationException: StaticInjectorError(n)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
TypeError: StaticInjectorError(n)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
at kt (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:95458)
at wt (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:95327)
at hr (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:119617)
at hr (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:119730)
at gr (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:119421)
at fr (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:119032)
at n (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:94456)
at mt (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:93978)
at Yt (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:101022)
at Xn (E:\TEST\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:2840:92062)
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync<T>(NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
```

**Comment by GRIMMR3AP3R** [comment]
I believe #632 also fixed this issue

**Comment by MarkPieszak** [comment]
Yeah I'm wondering if this was right before that commit, can you try with the latest - it should all be working now!

**Comment by vasyliv** [comment]
the same
![image](https://user-images.githubusercontent.com/19407350/40881457-cd2e43c8-66cf-11e8-883d-3e122bc8d04c.png)

**Comment by RZeni** [comment]
After some digging this appears to be a bug in the uglify plugin or the underlying uglify-es lib. Simply setting mangle to false is a temporary workaround for this issue.

**Comment by vasyliv** [comment]
@RZeni the problem is solved by 

> Simply setting mangle to false

, thanks.

**Comment by GRIMMR3AP3R** [comment]
Setting mangle to false doesn't "Fix" the issue it turns it off. A better fix is to preserve the class names.

**Comment by RZeni** [comment]
Closed my PR in favor of yours. It is def a better workaround, Thanks!
