### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hungbqit** [MarkPieszak/aspnetcore-angular2-universal#640]
I get an error when running with iis express (node 8.11.2, vs 2017):

-->  app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions
        {
          HotModuleReplacement = true,
          HotModuleReplacementEndpoint = "/dist/"
        });

System.AggregateException: One or more errors occurred. (Unexpected character encountered while parsing value: <. Path '', line 0, position 0.) ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Builder.WebpackDevMiddleware.UseWebpackDevMiddleware(IApplicationBuilder appBuilder, WebpackDevMiddlewareOptions options)
   at AspCoreServer.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, SpaDbContext context) in C:\Users\hungbqit\Desktop\aspnetcore-angular2-universal-master\Startup.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Server.IISIntegration.IISSetupFilter.<>c__DisplayClass4_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
---> (Inner Exception #0) Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync[T](NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync[T](CancellationToken cancellationToken, String moduleName, String exportNameOrNull, Object[] args)
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken)<---

**Comment by Flood** [comment]
Maybe bad formatted language files? Verify your json at https://jsonformatter.curiousconcept.com

**Comment by hungbqit** [comment]
I think there are some issues in my development environment. I have reinstalled .NET Core 2.1 SDK and everything was working fine. Thanks you!

**Comment by west1989** [comment]
How did you solve it? I have a same issue

**Comment by hungbqit** [comment]
I have this error with Microsoft.NETCore.App v2.1.0.
Everything is back to normal when I downgrade to version 2.0.7.
A few days ago, version 2.1.1 also worked well.

**Comment by west1989** [comment]
which version have you installed? I installed this [download](https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300)

**Comment by hungbqit** [comment]
Try this version:
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.301-windows-x64-installer

**Comment by alexbenitez** [comment]
I have tried all the different sdk version mentioned here. Any other idea of why the starter fail this way?

**Comment by MarkPieszak** [comment]
There are many different versions of the SDK and runtime and a lot seemed to have had breaking changes :(
This makes it difficult for packages/libraries to keep up with everything and what versions people have installed on their machine. It's a total pain!

Everything seems to be working fine locally, and I have dotnet 2.1.300 installed. Give it a shot with the latest template version? @alexbenitez 	

If anything, open up a new issue, maybe you're running into something different and either myself or others can try and help!

**Comment by alexbenitez** [comment]
Thanks @MarkPieszak. Yes, my issue apparently was related to a mix of run-times that I had installed. It started to work when I installed from this link (which matches the version you mention)

https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.3-windows-hosting-bundle-installer

**Comment by alexbenitez** [comment]
Hi @MarkPieszak... I started to get the same error... I tried without antivirus/firewalls/proxies, etc... to see if it is an environmental thing but unfortunately I can't figure out... is there any way that we can get the HTML that NodeServices is attempting to de-serialize?  How exactly can we use the `DebuggingPort = 9229;` setting to debug this (if possible)?

PS: I get the error with all the 2.1.3xx and 2.1.4xx .net core sdks

**Comment by alexbenitez** [comment]
@MarkPieszak ... finally I found the way to reproduce the issue and make it work (in my case)... I had to add `AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`  to the program.cs

```
  public static void Main (string[] args) {
        AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
         var host = BuildWebHost (args);
         using (var scope = host.Services.Cr
```

What exactly does this line do that causes the crash when using the middleware? Is this related to the corporate proxy (without it still crashes without the proxy).
