### ISSUE TITLE
Cannot read property 'properties' of undefined (npm run build:vendor)

### ISSUE THREAD

**Issue by alexbenitez** [MarkPieszak/aspnetcore-angular2-universal#690]
I got the latest starter and getting the following error when the script does "npm run build:vendor"... Something related to the describe: optionsSchema.definitions.output.properties.path.description (properties is undefined).

```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (D:\Alejandro\aspnetcore-angular2-universal-master\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at D:\Alejandro\aspnetcore-angular2-universal-master\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (D:\Alejandro\aspnetcore-angular2-universal-master\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular6-aspnetcore-universal@1.0.0-rc4 build:vendor: `webpack --config webpack.config.vendor.js --progress --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular6-aspnetcore-universal@1.0.0-rc4 build:vendor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Benitez.A\AppData\Roaming\npm-cache\_logs\2018-10-10T03_33_31_740Z-debug.log
```

and this is the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:vendor' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prebuild:vendor', 'build:vendor', 'postbuild:vendor' ]
5 info lifecycle angular6-aspnetcore-universal@1.0.0-rc4~prebuild:vendor: angular6-aspnetcore-universal@1.0.0-rc4
6 info lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: angular6-aspnetcore-universal@1.0.0-rc4
7 verbose lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: unsafe-perm in lifecycle true
8 verbose lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Alejandro\aspnetcore-angular2-universal-master\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Benitez.A\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Microsoft MPI\Bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft SQL Server\110\DTS\Binn;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\PrivateAssemblies;D:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft VS Code\bin;D:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files (x86)\dotnet;C:\Users\Benitez.A\AppData\Local\Microsoft\WindowsApps;C:\Users\Benitez.A\AppData\Roaming\npm;C:\Users\Benitez.A\.dotnet\tools
9 verbose lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: CWD: D:\Alejandro\aspnetcore-angular2-universal-master
10 silly lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: Args: [ '/d /s /c',
10 silly lifecycle   'webpack --config webpack.config.vendor.js --progress --color' ]
11 silly lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: Returned: code: 1  signal: null
12 info lifecycle angular6-aspnetcore-universal@1.0.0-rc4~build:vendor: Failed to exec build:vendor script
13 verbose stack Error: angular6-aspnetcore-universal@1.0.0-rc4 build:vendor: `webpack --config webpack.config.vendor.js --progress --color`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid angular6-aspnetcore-universal@1.0.0-rc4
15 verbose cwd D:\Alejandro\aspnetcore-angular2-universal-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:vendor"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error angular6-aspnetcore-universal@1.0.0-rc4 build:vendor: `webpack --config webpack.config.vendor.js --progress --color`
22 error Exit status 1
23 error Failed at the angular6-aspnetcore-universal@1.0.0-rc4 build:vendor script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by alexbenitez** [comment]
upgrading from `"webpack-cli": "^2.1.4"` to `"webpack-cli": "3.1.1"` fixed the problem.... Not sure if this is the correct/compatible version that we are supposed to use....

**Comment by chrisjmccrum** [comment]
thank you @alexbenitez I had the same issue and that resolved it for me

**Comment by MarkPieszak** [comment]
Thank you @alexbenitez 	!
Fixed and patched via 53eb532

**Comment by guimeisang** [comment]
> upgrading from `"webpack-cli": "^2.1.4"` to `"webpack-cli": "3.1.1"` fixed the problem.... Not sure if this is the correct/compatible version that we are supposed to use....

work

**Comment by ghost** [comment]
@alexbenitez  Worked for me as well Thanks !!
